GET localhost:8000/mohanlal/

GET localhost:8000/vijay/

GET localhost:8000/surya/

GET localhost:8000/mammootty/

GET localhost:8000/dhanush/

GET localhost:8000/ranbir/

GET localhost:8000/aditya/

GET localhost:8000/srk/

GET localhost:8000/ranveer/

GET localhost:8000/aamir/

GET localhost:8000/kamal/

GET localhost:8000/rajini/

GET localhost:8000/nivin/

GET localhost:8000/asif/

GET localhost:8000/dulquer/